skip-check:
  # t-class instances
  - CKV_AWS_135   # EBS-optimised (t2.micro can't)
  - CKV_AWS_126   # detailed monitoring (t2.micro free-tier)

  # IAM role – academy learner accounts can’t attach one
  - CKV2_AWS_41

  # Public subnets / SG rules you *intentionally* keep open for the demo
  - CKV_AWS_130   # map_public_ip_on_launch = true
  - CKV_AWS_23    # SG description – already present, but rule still triggers
  - CKV_AWS_260   # HTTP 0.0.0.0/0 allowed
  - CKV_AWS_382   # wide egress 0.0.0.0/0
  - CKV2_AWS_5    # SG attached check (false–positive with self-refs)

  # RDS hard-enterprise features you **cannot** enable in free labs
  - CKV_AWS_157   # Multi-AZ
  - CKV_AWS_293   # deletion protection
  - CKV_AWS_354   # PI KMS CMK
  - CKV_AWS_129   # export error log to CW
  - CKV2_AWS_30   # PG query logging
  - CKV2_AWS_60   # copy-tags-to-snapshots

  # VPC FlowLogs / default-SG lockdown – not required for Capstone
  - CKV2_AWS_11
  - CKV2_AWS_12
