name: IaC-SAST
on:
  push:
    paths: [ 'iac/**.tf' ]
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac
          output_format: cli
          output_file_path: sast-scan-report/checkov.txt
