name: IaC-SAST
on:
  push:
    paths: [ 'iac/**.tf','.github/workflows/sast.yml' ]
jobs:
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac
          output_format: cli
          output_file_path: sast-scan-report/checkov.txt
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: sast-scan-report/checkov.txt